Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /users/login/?next=/ HTTP/1.1" 200 1093
"GET /static/users/css/login_style.css HTTP/1.1" 304 0
"GET /static/users/images/login_logo.png HTTP/1.1" 304 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /users/login/?next=/ HTTP/1.1" 200 1093
"POST /users/login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2632
"GET /users/profile/ HTTP/1.1" 200 3658
C:\study\Python\z2_softarex\webapp\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2632
Internal Server Error: /users/profile/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[bit]
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\forms\boundfield.py", line 63, in __getitem__
    raise TypeError(
TypeError: BoundField indices must be integers or slices, not str.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 722, in resolve
    obj = self.var.resolve(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 901, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\forms\boundfield.py", line 259, in id_for_label
    id_ = widget.attrs.get("id") or self.auto_id
AttributeError: 'IntegerField' object has no attribute 'attrs'
"GET /users/profile/ HTTP/1.1" 500 222847
C:\study\Python\z2_softarex\webapp\users\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /users/profile/ HTTP/1.1" 200 3658
Watching for file changes with StatReloader
"GET /users/profile/ HTTP/1.1" 200 3646
Watching for file changes with StatReloader
"GET /users/profile/ HTTP/1.1" 200 3663
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2632
"GET /users/profile/ HTTP/1.1" 200 3664
C:\study\Python\z2_softarex\webapp\users\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2632
"GET /users/profile/ HTTP/1.1" 200 3662
Watching for file changes with StatReloader
"GET /users/profile/ HTTP/1.1" 200 3672
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 22, in head
    return render(request, 'main/index.html', data)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'categories' not found. 'categories' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 193384
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2056
"GET /static/main/css/styles.css HTTP/1.1" 304 0
"GET /static/main/images/logo.png HTTP/1.1" 304 0
"GET /users/profile/ HTTP/1.1" 200 3672
"GET /model/ HTTP/1.1" 200 2972
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /users/login/?next=/ HTTP/1.1" 200 1093
"GET /static/users/images/login_logo.png HTTP/1.1" 304 0
"GET /static/users/css/login_style.css HTTP/1.1" 304 0
"POST /users/login/?next=/ HTTP/1.1" 200 1241
"POST /users/login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2972
"GET /users/profile/ HTTP/1.1" 200 3672
"GET / HTTP/1.1" 200 2056
"GET /users/profile/ HTTP/1.1" 200 3672
"GET /model/ HTTP/1.1" 200 2972
"GET /contact/ HTTP/1.1" 200 27
"GET /model/ HTTP/1.1" 200 2972
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2972
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /model/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 178, in get
    return super().get(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 100, in get_form_class
    model = self.get_queryset().model
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\detail.py", line 72, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: MakeCalculations is missing a QuerySet. Define MakeCalculations.model, MakeCalculations.queryset, or override MakeCalculations.get_queryset().
"GET /model/ HTTP/1.1" 500 103866
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2056
Internal Server Error: /model/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 178, in get
    return super().get(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 36, in get_form
    form_class = self.get_form_class()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 100, in get_form_class
    model = self.get_queryset().model
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\detail.py", line 72, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: MakeCalculations is missing a QuerySet. Define MakeCalculations.model, MakeCalculations.queryset, or override MakeCalculations.get_queryset().
"GET /model/ HTTP/1.1" 500 103729
C:\study\Python\z2_softarex\webapp\users\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2709
Watching for file changes with StatReloader
Internal Server Error: /model/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 40, in form_valid
    return super().form_valid(form)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 119, in get_success_url
    if self.success_url:
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'head' not found. 'head' is not a valid view function or pattern name.
"POST /model/ HTTP/1.1" 500 120213
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /model/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2709
"POST /model/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2056
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2709
"POST /model/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2709
"POST /model/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2056
"GET /model/ HTTP/1.1" 200 2709
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 19, in head
    return render(request, 'main/index.html', data)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contact' not found. 'contact' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 188203
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
Internal Server Error: /model/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'contact' not found. 'contact' is not a valid view function or pattern name.
"GET /model/ HTTP/1.1" 500 176406
C:\study\Python\z2_softarex\webapp\users\context_processors.py changed, reloading.
Watching for file changes with StatReloader
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 46, in result
    return render(request, 'main/result.html', {'calc': Calculations.objects.latest()})
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\db\models\query.py", line 1092, in latest
    return self.reverse()._earliest(*fields)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\db\models\query.py", line 1067, in _earliest
    raise ValueError(
ValueError: earliest() and latest() require either fields as positional arguments or 'get_latest_by' in the model's Meta.
"GET /model/result HTTP/1.1" 500 81657
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2023
Not Found: /model/photos/2025/06/19/view_HelRAYy.jpg
"GET /model/photos/2025/06/19/view_HelRAYy.jpg HTTP/1.1" 404 3456
"GET / HTTP/1.1" 200 1954
"GET / HTTP/1.1" 200 1954
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /users/login/?next=/ HTTP/1.1" 200 1093
"POST /users/login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2031
Not Found: /media/photos/2025/06/19/MVt_Mz9SpP3.jpg
"GET /media/photos/2025/06/19/MVt_Mz9SpP3.jpg HTTP/1.1" 404 3453
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2026
Not Found: /media/photos/2025/06/19/image002.jpg
"GET /media/photos/2025/06/19/image002.jpg HTTP/1.1" 404 3444
C:\study\Python\z2_softarex\webapp\main\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /model/result HTTP/1.1" 200 2026
"GET /media/photos/2025/06/19/image002.jpg HTTP/1.1" 200 25525
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
Internal Server Error: /model/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 42, in form_valid
    w.result = calculate(w.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 98, in calculate
    img = transform(Image.open(path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/img_test1.jpg'
"POST /model/ HTTP/1.1" 500 101342
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 98, in calculate
    img = transform(Image.open(path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/photos/2025/06/19/img_test1.jpg'
"GET /model/result HTTP/1.1" 500 77283
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 101, in calculate
    img = transform(Image.open(BASE_DIR / path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\media\\photos\\2025\\06\\19\\img_test1_yCVEZnu.jpg'
"GET /model/result HTTP/1.1" 500 77404
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 101, in calculate
    img = transform(Image.open(BASE_DIR / path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\media\\photos\\2025\\06\\19\\img_test1_NRijWKf.jpg'
"GET /model/result HTTP/1.1" 500 77404
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 101, in calculate
    img = transform(Image.open(BASE_DIR / path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\media\\photos\\2025\\06\\19\\img_test1_l3zZi9s.jpg'
"GET /model/result HTTP/1.1" 500 77404
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 101, in calculate
    img = transform(Image.open(BASE_DIR / path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\media\\photos\\2025\\06\\19\\img_test1_U1Uza9E.jpg'
"GET /model/result HTTP/1.1" 500 77404
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 101, in calculate
    img = transform(Image.open(BASE_DIR / path)).unsqueeze_(0)
TypeError: unsupported operand type(s) for /: 'str' and 'str'
"GET /model/result HTTP/1.1" 500 72389
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(os.path.join(os.path.abspath(__file__), path))).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/media/photos/2025/06/19/img_test1_BHoGXP9.jpg'
"GET /model/result HTTP/1.1" 500 77427
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(os.path.join(os.path.abspath(__file__)))).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3572, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\study\\Python\\z2_softarex\\webapp\\main\\model_django.py'
"GET /model/result HTTP/1.1" 500 79556
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(BASE_DIR)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'C:\\study\\Python\\z2_softarex\\webapp'
"GET /model/result HTTP/1.1" 500 77272
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(os.path.join(BASE_DIR, path))).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/media/photos/2025/06/19/img_test1_nsmdgDD.jpg'
"GET /model/result HTTP/1.1" 500 77393
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
"GET /model/ HTTP/1.1" 200 2580
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/photos/2025/06/19/img_test1_2LE63Db.jpg'
"GET /model/result HTTP/1.1" 500 77427
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(os.path.join('C:\\study\\Python\\z2_softarex\\webapp', path))).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/media/photos/2025/06/19/img_test1.jpg'
"GET /model/result HTTP/1.1" 500 77521
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(os.path.join(str(BASE_DIR), str(path)))).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/media/photos/2025/06/19/img_test1_lFI6Xtz.jpg'
"GET /model/result HTTP/1.1" 500 77505
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test1_uFgaLcw.jpg HTTP/1.1" 200 1616
C:\study\Python\z2_softarex\webapp\main\model_django.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test1_88T4vmF.jpg HTTP/1.1" 200 1616
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test1_akZCHmj.jpg HTTP/1.1" 200 1616
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test1_utxcJ8v.jpg HTTP/1.1" 200 1616
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test1_uSwGNL1.jpg HTTP/1.1" 200 1616
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2029
"GET /media/photos/2025/06/19/img_test2.jpg HTTP/1.1" 200 1514
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\db\models\fields\files.py", line 69, in url
    self._require_file()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\db\models\fields\files.py", line 44, in _require_file
    raise ValueError(
ValueError: The 'img' attribute has no file associated with it.
"GET /model/result HTTP/1.1" 500 76158
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test2_g4cFhUt.jpg HTTP/1.1" 200 1514
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(path)).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/photos/2025/06/19/img_test1_FOV1ZWY.jpg'
"GET /model/result HTTP/1.1" 500 77394
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 47, in result
    obj.result = calculate(obj.img.url)
  File "C:\study\Python\z2_softarex\webapp\main\model_django.py", line 100, in calculate
    img = transform(Image.open(str(path))).unsqueeze_(0)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\PIL\Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/photos/2025/06/19/img_test1_z5G9BGb.jpg'
"GET /model/result HTTP/1.1" 500 77404
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2029
"GET /media/photos/2025/06/19/img_test1.jpg HTTP/1.1" 200 1616
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2029
"GET /media/photos/2025/06/19/img_test1.jpg HTTP/1.1" 200 1616
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2029
"GET /media/photos/2025/06/19/img_test2.jpg HTTP/1.1" 200 1514
"GET /model/ HTTP/1.1" 200 2580
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2040
"GET /media/photos/2025/06/19/PrivateTest_10086748.jpg HTTP/1.1" 200 1224
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2391
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2048
"GET /media/photos/2025/06/19/PrivateTest_10086748_OoOfP8F.jpg HTTP/1.1" 200 1224
Watching for file changes with StatReloader
"GET /model/ HTTP/1.1" 200 2391
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2037
"GET /media/photos/2025/06/19/img_test1_mli6t21.jpg HTTP/1.1" 200 1616
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /static/main/css/styles.css HTTP/1.1" 304 0
"GET /static/main/images/logo.png HTTP/1.1" 304 0
"GET /model/ HTTP/1.1" 200 2391
"POST /model/ HTTP/1.1" 302 0
Internal Server Error: /model/result
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 53, in result
    return render(request, 'main/result.html', {'obj': obj})
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'download_pdf' not found. 'download_pdf' is not a valid view function or pattern name.
"GET /model/result HTTP/1.1" 500 168320
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2391
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2089
"GET /media/photos/2025/06/20/img_test1.jpg HTTP/1.1" 200 1616
"GET /download/result/ HTTP/1.1" 200 79
"GET /download/result/ HTTP/1.1" 200 79
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1954
"GET /model/ HTTP/1.1" 200 2391
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 2089
"GET /media/photos/2025/06/20/img_test2.jpg HTTP/1.1" 200 1514
"GET /download/result/ HTTP/1.1" 200 1501
"GET /download/result/ HTTP/1.1" 200 1501
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1503
"GET / HTTP/1.1" 200 1503
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1492
"GET /model/ HTTP/1.1" 200 1966
"GET / HTTP/1.1" 200 1492
"GET /model/ HTTP/1.1" 200 1966
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'users.context_processors' has no attribute 'get_women_context'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\study\Python\z2_softarex\webapp\main\views.py", line 23, in head
    return render(request, 'main/index.html', data)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "C:\Users\baran\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\context.py", line 256, in bind_template
    processors = template.engine.template_context_processors + self._processors
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\engine.py", line 118, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\engine.py", line 118, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "users.context_processors" does not define a "get_women_context" attribute/class
"GET / HTTP/1.1" 500 127229
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET /model/ HTTP/1.1" 200 1934
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
C:\study\Python\z2_softarex\webapp\main\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"GET /users/profile/ HTTP/1.1" 200 3131
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET / HTTP/1.1" 200 1476
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"GET /users/profile/ HTTP/1.1" 200 3071
"GET /users/profile/ HTTP/1.1" 200 3071
"GET /users/profile/ HTTP/1.1" 200 3071
"GET /users/profile/ HTTP/1.1" 200 3071
"POST /users/profile/ HTTP/1.1" 302 0
"GET /users/profile/ HTTP/1.1" 200 3071
"GET /users/password-change HTTP/1.1" 200 2548
"POST /users/logout/ HTTP/1.1" 302 0
"GET /users/login/ HTTP/1.1" 200 1011
"GET /static/users/images/login_logo.png HTTP/1.1" 304 0
"GET /static/users/css/login_style.css HTTP/1.1" 304 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /users/login/?next=/ HTTP/1.1" 200 1002
"GET /users/register/ HTTP/1.1" 200 1760
"GET /users/login/?next=/ HTTP/1.1" 200 1002
"POST /users/login/?next=/ HTTP/1.1" 200 1150
"POST /users/login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 1476
"GET / HTTP/1.1" 200 1476
"GET /model/ HTTP/1.1" 200 1934
"GET /about/ HTTP/1.1" 200 1473
"GET /model/ HTTP/1.1" 200 1934
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 1657
"GET /media/photos/2025/06/20/img_test1_MbYLfMh.jpg HTTP/1.1" 200 1616
"GET /download/result/ HTTP/1.1" 200 1513
"GET /users/profile/ HTTP/1.1" 200 3058
"GET /users/password-change HTTP/1.1" 200 2548
"GET /users/profile/ HTTP/1.1" 200 3058
"POST /users/profile/ HTTP/1.1" 302 0
"GET /users/profile/ HTTP/1.1" 200 3058
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET / HTTP/1.1" 200 1476
"GET /users/profile/ HTTP/1.1" 200 3058
"POST /users/logout/ HTTP/1.1" 302 0
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\defaulttags.py", line 1421, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\study\Python\z2_softarex\djvenv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':login' from 'users:login'
"GET /users/login/ HTTP/1.1" 500 171338
"GET /users/login/ HTTP/1.1" 200 1032
"GET /users/login/ HTTP/1.1" 200 1032
"GET /users/register/ HTTP/1.1" 200 1790
"GET /users/login/ HTTP/1.1" 200 1032
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /users/login/?next=/ HTTP/1.1" 200 1032
"GET /static/users/css/login_style.css HTTP/1.1" 304 0
"GET /static/users/images/login_logo.png HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3898
"POST /users/login/?next=/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 1476
"GET /static/main/css/styles.css HTTP/1.1" 304 0
"GET /static/main/images/logo.png HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 1476
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET /model/ HTTP/1.1" 200 1934
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1476
"GET /model/ HTTP/1.1" 200 2121
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2038
"GET /about/ HTTP/1.1" 200 2754
"GET /model/ HTTP/1.1" 200 1934
"POST /model/ HTTP/1.1" 302 0
"GET /model/result HTTP/1.1" 200 1657
"GET /media/photos/2025/06/20/img_test1_L9bdGYF.jpg HTTP/1.1" 200 1616
"GET /download/result/ HTTP/1.1" 200 1513
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2038
"GET /static/main/css/styles.css HTTP/1.1" 304 0
"GET /static/main/images/logo.png HTTP/1.1" 304 0
"GET /about/ HTTP/1.1" 200 2754
